# Generated by Django 5.2.1 on 2025-06-03 12:59

import core.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('anotacoes_anteriores', core.fields.EncryptedTextField(blank=True, null=True)),
                ('anotacoes_atuais', core.fields.EncryptedTextField()),
                ('pontos_atencao', core.fields.EncryptedTextField(blank=True, null=True)),
                ('agendamento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='consulta', to='agendamentos.agendamento')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_criado_por', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_modificado_por', to=settings.AUTH_USER_MODEL)),
                ('profissional_responsavel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultas_realizadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-agendamento__data', '-agendamento__hora'],
            },
        ),
    ]
